name: Deploy to Private VM via OpenVPN

on:
  push:
    branches:
      - main
      - master

  pull_request:
    types: [closed]
    branches:
      - main
      - master

jobs:
  deploy:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: PHP Setup
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, xml, curl, zip, mysql, bcmath, gd
          tools: composer
      
      - name: Node.js setup
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Composer
        run: composer install --prefer-dist --no-progress --no-dev --optimize-autoloader

      - name: Install NPM
        run: npm install

      - name: Building React Asset
        run: npm run build

      - name: making .env
        run: echo '${{ secrets.DOT_ENV }}' > .env

      - name: create secrets directory
        run: mkdir -p storage/app/secrets

      - name: add service account key info
        run: echo '${{ secrets.SERVICE_ACCOUNT }}' > storage/app/secrets/healthy-spark-458003-h1-26f5513893cc.json
         
      - name: Connect to University OpenVPN
        uses: kota65535/github-openvpn-connect-action@v2 
        id: connect_vpn
        with:
          config_file: .github/workflows/myitsvpn-5025231268@student.its.ac.id.ovpn
          username: ${{ secrets.OVPN_USERNAME }}
          password: ${{ secrets.OVPN_PASSWORD }}
          
      - name: Wait for VPN link to come up
        run: sleep 10 

      - name: Menyinkronkan File ke Server (AEnterprise)
        uses: AEnterprise/rsync-deploy@v1.0.2
        env:
          DEPLOY_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-avzr --delete"
          SERVER_IP: ${{ secrets.SSH_HOST }}
          USERNAME: ${{ secrets.SSH_USERNAME }}
          SERVER_PORT: "22"
          FOLDER: "./"
          SERVER_DESTINATION: "/var/www/mona"
          EXCLUDE: ".git/,.github/,node_modules/"

      - name: Run deployment script
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            bash ~/deploy.sh
            
      - name: Disconnect VPN
        if: always()
        run: |
          sudo killall openvpn || true
